[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
# Глобальні налаштування
line-length = 88
exclude = ["venv", "infra", ".devcontainer"]

[tool.ruff.lint]
# Налаштування саме перевірок коду (linter)
select = ["E", "F", "W", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["venv", "infra"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
